#!/usr/bin/env bash

readonly binaries_loc='/usr/sbin'


readonly power_hibernate="$binaries_loc/pm-hibernate"
readonly power_suspend="$binaries_loc/pm-suspend"
readonly power_shutdown="/sbin/shutdown now"
declare cmd_to_run=''
declare -ri locktime=120

powerman::lock() {
    nohup i3lock -c 4A4A4A > /dev/null
}

powerman::run() {
    powerman::lock
    sudo $1
}

if [[ $# != '0' ]]; then
    case "$1" in
        hibernate)
            pkill keepassxc
            powerman::run "$power_hibernate"
            ;;
        suspend)
            powerman::run "$power_suspend"
            ;;
        autolock)
            monitor_status=$(xset q | grep Monitor | cut -d' ' -f5)
            if [ "$monitor_status" == "Off" ]; then
                pretime=$(date +%s)
                sudo $power_suspend

                curtime=$(date +%s)
                if [ $(($curtime - $pretime)) -ge $locktime ]; then
                    powerman::lock
                fi
            else
                echo "Not locking; screen not off"
            fi
            ;;
        lock)
            powerman::lock
            ;;
        *)
            echo "Invalid argument: '$1'"
            exit 1
            ;;
    esac
else # default command
    powerman::run "$power_suspend"
fi
